<?php

namespace tgalfa\RepoService\Tests\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Str;

class TestModelFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        $name = $this->faker->name();

        return [
            'name' => $name,
            'slug' => Str::of($name)->slug('-'),
            'type' => $this->faker->word,
        ];
    }

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        $resolver = static::$modelNameResolver ?: function (self $factory) {
            $factoryBasename = Str::replaceLast('Factory', '', class_basename($factory));

            $appNamespace = 'tgalfa\\RepoService\\Tests\\';

            return class_exists($appNamespace.'Models\\'.$factoryBasename)
                        ? $appNamespace.'Models\\'.$factoryBasename
                        : $appNamespace.$factoryBasename;
        };

        return $this->model ?: $resolver($this);
    }
}
